version: 2
jobs:
  build:
    machine: true
    context: org-global
    steps:
      - checkout
      - run: echo $DOCKER_USER
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run: docker build . -t jchancehud/libstorj:latest
