version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: ? |
        docker build . -t jchancehud/libstorj:latest
        docker push jchancehud/libstorj:latest
      - run: ? |
        cd ubuntu
        docker build . -t jchancehud/libstorj:ubuntu
        docker push jchancehud/libstorj:ubuntu
  build_nonmaster:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build . -t jchancehud/libstorj:$CIRCLE_BRANCH
      - run: docker push jchancehud/libstorj:$CIRCLE_BRANCH
      - run: cd ubuntu && docker build . -t jchancehud/libstorj:ubuntu-$CIRCLE_BRANCH && docker push jchancehud/libstorj:ubuntu-$CIRCLE_BRANCH

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - build_nonmaster:
          filters:
            branches:
              ignore: master
