# multiline build commands should be put here to avoid a bug with multine
# strings in lists
boot: &Boot |
  docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  export DOCKER_REPO=jchancehud/libstorj

alpine_master: &AlpineMaster *Boot |
  cd alpine
  docker build . -t $DOCKER_REPO:alpine
  docker push $DOCKER_REPO:alpine
ubuntu_master: &UbuntuMaster *Boot |
  cd ubuntu
  docker build . -t $DOCKER_REPO:ubuntu
  docker push $DOCKER_REPO:ubuntu
  # Tag latest off of ubuntu
  docker tag $DOCKER_REPO:ubuntu $DOCKER_REPO:latest
  docker push $DOCKER_REPO:latest

alpine_nonmaster: &AlpineNonmaster *Boot |
  cd alpine
  docker build . -t $DOCKER_REPO:alpine-$CIRCLE_BRANCH
  docker push $DOCKER_REPO:alpine-$CIRCLE_BRANCH
ubuntu_nonmaster: &UbuntuNonmaster *Boot |
  cd ubuntu
  docker build . -t $DOCKER_REPO:ubuntu-$CIRCLE_BRANCH
  docker push $DOCKER_REPO:ubuntu-$CIRCLE_BRANCH

# circleci config
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: *AlpineMaster
      - run: *UbuntuMaster
  build_nonmaster:
    machine: true
    steps:
      - checkout
      - run: *AlpineNonmaster
      - run: *UbuntuNonmaster
workflows:
  version: 2
  build_all:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
      - build_nonmaster:
          context: org-global
          filters:
            branches:
              ignore: master
